apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:3000']

      - job_name: 'loki'
        static_configs:
          - targets: ['loki:3100']

      - job_name: 'springboot-rabbitmq'
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ['springboot-rabbitmq:8082']
            labels:
              application: "springboot-rabbitmq"

      - job_name: 'api-teste'
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ['api-teste:8383']
            labels:
              application: "api-teste"

      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq-stack:9419']
            labels:
              application: "rabbitmq"

      - job_name: 'rabbitmq-management'
        metrics_path: "/metrics"
        static_configs:
          - targets: ['rabbitmq-stack:15672']
            labels:
              application: "rabbitmq-management"
