apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: argocd
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: spring3-cassandra
        static_configs:
          - targets:
              - localhost
            labels:
              job: spring3-cassandra
              app: spring3-cassandra
              __path__: /var/log/containers/*spring3-cassandra*.log
